name: Deploy Quarto Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Specify the R version you need

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("quarto", "rmarkdown"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.553  # Specify a valid Quarto version explicitly

      - name: Render Quarto site
        run: |
          quarto render qmd --to html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: qmd/_site  # Adjust this path if your output directory is different
          destination_dir: .      # Publish to the root of the gh-pages branch
