name: Deploy Quarto Site to GitHub Pages
permissions: 
    contents: write
    pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Specify the R version you need

      # TODO: use renv instead [ref](https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md#using-renv-to-manage-r-packages)
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("quarto", "rmarkdown", "ggplot2", "here"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
